---

  - include_tasks: ../../bigiqRefreshToken/tasks/refreshToken.yml
  
  - name: POST - using REST proxy to associated signature set to Parent Policy on BIG-IPs
    uri:
      url: "https://{{bigiq}}/mgmt/shared/resolver/device-groups/cm-bigip-allBigIpDevices/devices/{{item.value.machineId}}/rest-proxy/mgmt/tm/asm/policies/{{parentPolicyId}}/signature-sets"
      method: POST
      validate_certs: no
      headers:
        X-F5-Auth-Token: "{{bigiqTokens.accessToken}}"
      body:
        signatureSetReference:
          link: https://localhost/mgmt/tm/asm/signature-sets/{{getSigSetId}}
      body_format: json
      status_code: 201
    delegate_to: localhost
    loop: "{{ bigipDevicesDict|dict2items }}"
    register: postAssociateSetToPolicy
    when: item.value.ASMdiscovered == true

  - name: Print result of POST to associate Signature Set to Parent Policy
    debug:
      msg: "{{postAssociateSetToPolicy}}"
      verbosity: 3

  