---
      
  - include_tasks: ../../bigiqRefreshToken/tasks/refreshToken.yml

  - name: PATCH - using REST proxy enforce signatures 
    uri:
      url: "https://{{bigiq}}/mgmt/shared/resolver/device-groups/cm-bigip-allBigIpDevices/devices/{{outer_item.value.machineId}}/rest-proxy/mgmt/tm/asm/policies/{{middle_item.value.id}}/signatures/{{item}}"
      method: PATCH
      validate_certs: no
      headers:
        X-F5-Auth-Token: "{{bigiqTokens.accessToken}}"
      body:
        performStaging: "false"
      body_format: json
      status_code: 200
    delegate_to: localhost
    loop: "{{ signatureIdsUUID }}"
    register: patchEnforceSignatures

  - name: Print result of PATCH to associate signature set to Child Policy
    debug:
      msg: "{{patchEnforceSignatures}}"
      verbosity: 3

  