---

  - include_tasks: ../../bigiqRefreshToken/tasks/refreshToken.yml

  - name: GET - status information from currently installed Signature file
    uri:
      url: "https://{{bigiq}}/mgmt/shared/resolver/device-groups/cm-bigip-allBigIpDevices/devices/{{item.value.machineId}}/rest-proxy/mgmt/tm/live-update/asm-attack-signatures/installations?$select=status,id"
      method: GET
      validate_certs: no
      headers:
        X-F5-Auth-Token: "{{bigiqTokens.accessToken}}"
    delegate_to: localhost
    loop: "{{ bigipDevicesDict|dict2items }}"
    register: getSigCurrentlyInstalled
    when: item.value.ASMdiscovered == true


  - name: Print result of GET to find 
    debug:
      msg: "{{getSigCurrentlyInstalled}}"
      verbosity: 3

  