---

  - include_tasks: ../../bigiqRefreshToken/tasks/refreshToken.yml

  - name: GET - status of installation of Signature File
    uri:
      url: "https://{{bigiq}}/mgmt/shared/resolver/device-groups/cm-bigip-allBigIpDevices/devices/{{item.value.machineId}}/rest-proxy/mgmt/tm/live-update/asm-attack-signatures/installations?$select=status,id"
      method: GET
      validate_certs: no
      headers:
        X-F5-Auth-Token: "{{bigiqTokens.accessToken}}"
    delegate_to: localhost
    loop: "{{ bigipDevicesDict|dict2items }}"
    register: getSigFileIDrequest
    when: item.value.ASMdiscovered == true
    until: getSigFileIDrequest|json_query(query_json) == True
    vars:
       query_json: >
         json.items[*].status | contains(@,'staged')
    retries: 20
    delay: 15

  - name: Print result of GET to check status of installation of Signature File
    debug:
      msg: "{{getSigFileIDrequest}}"
      verbosity: 3